Homepage
GrinOleksandr/wovenly pull request #6
Opened 2019-04-30 07:45 UTC by GrinOleksandr

homepage ready!

2019-05-03 07:49 UTC, NickZaporozets commented on public/css/common.css
> +  padding-right: 0 !important;
Має працювати і без імпортентів

2019-05-03 07:51 UTC, NickZaporozets commented on public/css/mobile.css
>    display: flex;
Чи відповідає назва класу його суті?

2019-05-03 07:57 UTC, NickZaporozets commented on public/css/tablet-wide.css
> +    background-size: 9%;
це дивно

2019-05-03 07:57 UTC, NickZaporozets commented on public/css/tablet-wide.css
> +    background-size: 5%;
і це дивно

2019-05-03 07:58 UTC, NickZaporozets commented on public/css/tablet-wide.css
> +    background-size: 9%;
це теж дивно

2019-05-03 07:59 UTC, NickZaporozets commented on public/css/tablet.css
> +.sizes__item--wrapper:nth-child(3), .sizes__item--wrapper:nth-child(4) {
Це правило, здається, у всіх файлах однакове. Навіщо тоді дублювати?
Достатньо тримати це правило в mobile.css щоб воно було доступним всюди. Якщо є ще дублікати, то краще так не робити

2019-05-03 08:00 UTC, NickZaporozets commented on public/css/tablet.css
> +.footer-benefits {
Теж правило наче однакове у всіх файлах

2019-05-03 08:02 UTC, NickZaporozets commented on public/index.html
> -
Вище інклуди з крапкою-слеш `./`: `href="./css/desktop.css"`
а нижче інклуди без нічого на початку: `src="js/lib/polyfill_promise.min.js"`

2019-05-03 08:08 UTC, NickZaporozets commented on public/templates/discoverYourStyle.ejs
> +    <span class="discover-your-style__slide--title"><%= capitalizeAll(style) %></span>
Хіба в CSS не було б достатньо це зробити через декоратор? text-transform: uppercase

2019-05-03 08:10 UTC, NickZaporozets commented on src/newBlock.js
> +function getLocalStorageObjectItem(key) {
Це можна було винести в окремий файл, бо я бачу що не раз це прописується. Типу власну лібу створити, якщо функції викликаються більше одного разу і в різних місцях

2019-05-03 08:46 UTC, NickZaporozets requested changes
Comments above

2019-05-03 13:31 UTC, GrinOleksandr commented on public/css/tablet.css
> +.sizes__item--wrapper:nth-child(3), .sizes__item--wrapper:nth-child(4) {
ні, воно на мобайлі одне(дісплей = ноне), а на всіх інших друге!
так як на всйх девайсах загружається файл стилів мобайл та стилі для цього девайса, то доводиться перебивати стилі мобайла в кожному файлі!

2019-05-03 13:33 UTC, GrinOleksandr commented on public/css/tablet.css
> +.footer-benefits {
теж саме, воно не однакове, за мобайлом, а усі інші файли стилів незалежні один від одного, по підгружається лише один з них. в кожно маю перебивать стилі

2019-05-03 13:34 UTC, GrinOleksandr commented on public/index.html
> -
прибираю

2019-05-03 13:35 UTC, GrinOleksandr commented on public/templates/discoverYourStyle.ejs
> +    <span class="discover-your-style__slide--title"><%= capitalizeAll(style) %></span>
так, потім я уже це зрозумів і робив через декоратор, переробити це?

2019-05-03 13:53 UTC, GrinOleksandr commented on src/newBlock.js
> +function getLocalStorageObjectItem(key) {
done

2019-05-03 13:55 UTC, GrinOleksandr commented on public/css/common.css
> +  padding-right: 0 !important;
таки так, працює!

2019-05-03 13:59 UTC, GrinOleksandr commented on public/css/mobile.css
>    display: flex;
fixed 
new name cart-counter__displayed

2019-05-03 14:07 UTC, GrinOleksandr commented on public/css/tablet-wide.css
> +    background-size: 9%;
fixed to px.

2019-05-03 14:07 UTC, GrinOleksandr commented on public/css/tablet-wide.css
> +    background-size: 5%;
fixed to px.

2019-05-03 14:07 UTC, GrinOleksandr commented on public/css/tablet-wide.css
> +    background-size: 9%;
fixed to px.

2019-05-06 06:28 UTC, NickZaporozets commented on public/templates/discoverYourStyle.ejs
> +    <span class="discover-your-style__slide--title"><%= capitalizeAll(style) %></span>
Так, можна переробити :)

2019-05-06 07:15 UTC, GrinOleksandr commented on public/templates/discoverYourStyle.ejs
> +    <span class="discover-your-style__slide--title"><%= capitalizeAll(style) %></span>
Done

2019-05-06 07:15 UTC, GrinOleksandr commented on public/index.html
> -
Done

2019-05-06 07:19 UTC, GrinOleksandr commented on public/index.html
> -
oh, previously didn't notice some records, already fixed that.

2019-05-06 09:12 UTC, NickZaporozets approved these changes

2019-05-06 09:19 UTC, merged